# Generated by Django 2.1.15 on 2021-08-12 05:34

from django.db import migrations, models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=main.storage.FieldStorage(), upload_to='./filesupload')),
            ],
        ),
    ]
