# Generated by Django 2.1.15 on 2021-08-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
