# Generated by Django 2.1.15 on 2021-08-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210814_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('Average_fuel_consumption', models.FloatField()),
                ('Average_speed', models.FloatField()),
                ('Distance_travelled', models.FloatField()),
                ('Engine_RPM', models.FloatField()),
                ('Fuel_used', models.FloatField()),
                ('Vehicle_speed', models.FloatField()),
            ],
        ),
    ]
