# Generated by Django 2.1.15 on 2021-09-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_uploadfile_datetimeofupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('Average_fuel_consumption', models.FloatField()),
                ('Average_speed', models.FloatField()),
                ('Distance_travelled', models.FloatField()),
                ('Engine_RPM', models.FloatField()),
                ('Fuel_used', models.FloatField()),
                ('Vehicle_speed', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
