# Generated by Django 2.1.15 on 2021-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210912_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
